# Generated by Django 3.2.7 on 2021-10-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20211014_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
